FROM python:3.12-slim
WORKDIR /app
COPY client.py ./client.py
COPY load_server.py ./load_server.py

RUN pip install --no-cache-dir requests
RUN useradd -m labuser && chown -R labuser:labuser /app
USER labuser

CMD ["python", "load_server.py", "--url", "http://server:8088/"]